version: '2.3'
services:
  roscore:
    image: osrf/ros:melodic-desktop-full
    container_name: roscore
    network_mode: "host"
    privileged: true
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    command: bash -c ". /opt/ros/melodic/setup.bash; roscore"

  ros_navigation:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros:navigation-gui
    container_name: ros_navigation
    network_mode: "host"
    privileged: true
    tty: true
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    devices:
      - /dev/dri:/dev/dri
    command: /bin/bash

  rviz:
    image: osrf/ros:melodic-desktop-full
    container_name: rviz
    network_mode: "host"
    privileged: true
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    devices:
      - /dev/dri:/dev/dri
    command: bash -c ". /opt/ros/melodic/setup.bash; sleep 3; rviz"

